version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Ensure correct Node.js version
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Serverless version
      - serverless --version
      - echo Install source NPM dependencies
      - npm install
  build:
    commands:
      - echo Deployments started on `date`
      - echo "ENV_NAME is set to: $ENV_NAME"
      - echo Deploying with the Serverless Framework
      - serverless deploy -v -s $ENV_NAME --debug
  post_build:
    commands:
      - echo Deployment completed on `date`
